name: update readme
description: "update the notebook index in readme"
inputs:
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    required: true
  actor:
    description: "github.actor"
    required: true
  push_branch:
    description: "Target branch name to push the index"
    required: true
    default: "gh-page"
runs:
  using: "composite"
  steps:
  - name: Set up Python
    uses: actions/setup-python@v2
    with:
      python-version: '3.x'
  - name: update readme index
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/junxnone/linux/main/docs/_sidebar.md -O linux.md
      wget https://raw.githubusercontent.com/junxnone/xwiki/main/docs/_sidebar.md -O xwiki.md
      wget https://raw.githubusercontent.com/junxnone/aiwiki/main/docs/_sidebar.md -O aiwiki.md
      wget https://raw.githubusercontent.com/junxnone/opt/main/docs/_sidebar.md -O opt.md
      wget https://raw.githubusercontent.com/junxnone/samples/main/README.md -O samples.md
      echo "# Junxnone" |tee sitemap.md
      date  -d "+8 hour" "+> \`@%Y.%m.%d %H:%M:%S\`" | tee -a sitemap.md

      echo "## Linux" |tee -a sitemap.md
      cat linux.md |grep -v "Wiki History"|grep -v Junx |grep -v "\-\-\-" |sed 's/\](\//\](linux\//g'|tee -a sitemap.md
      echo "## X" |tee -a sitemap.md
      cat xwiki.md |grep -v "Wiki History"|grep -v Junx |grep -v "\-\-\-" |sed 's/\](\//\](xwiki\//g'|tee -a sitemap.md
      echo "## AI" |tee -a sitemap.md
      cat aiwiki.md |grep -v "Wiki History"|grep -v Junx |grep -v "\-\-\-" |sed 's/\](\//\](aiwiki\//g'|tee -a sitemap.md
      echo "## OPT" |tee -a sitemap.md
      cat opt.md |grep -v "Wiki History"|grep -v Junx |grep -v "\-\-\-" |sed 's/\](\//\](opt\//g'|tee -a sitemap.md
      cat samples.md |tee -a sitemap.md

      wget https://raw.githubusercontent.com/junxnone/linux/main/docs/hist.md -O linux_hist.md
      wget https://raw.githubusercontent.com/junxnone/xwiki/main/docs/hist.md -O xwiki_hist.md
      wget https://raw.githubusercontent.com/junxnone/aiwiki/main/docs/hist.md -O aiwiki_hist.md
      wget https://raw.githubusercontent.com/junxnone/opt/main/docs/hist.md -O opt_hist.md
      cat linux_hist.md |grep -v 'Wiki History'|sed 's/\](\//\](linux\//g'|tee tmp.md
      cat xwiki_hist.md |grep -v 'Wiki History'|sed 's/\](\//\](xwiki\//g'|tee -a tmp.md
      cat aiwiki_hist.md |grep -v 'Wiki History'|sed 's/\](\//\](aiwiki\//g'|tee -a tmp.md
      cat opt_hist.md |grep -v 'Wiki History'|sed 's/\](\//\](opt\//g'|tee -a tmp.md
      
      cat tmp.md |sort -r | tee sitehist.md
      date  -d "+8 hour" "+> \`@%Y.%m.%d %H:%M:%S\`" | tee -a sitehist.md

      wget https://raw.githubusercontent.com/junxnone/linux/main/docs/kg.json -O linux_kg.json
      wget https://raw.githubusercontent.com/junxnone/xwiki/main/docs/kg.json -O xwiki_kg.json
      wget https://raw.githubusercontent.com/junxnone/aiwiki/main/docs/kg.json -O aiwiki_kg.json
      wget https://raw.githubusercontent.com/junxnone/opt/main/docs/kg.json -O opt_kg.json
      wget https://raw.githubusercontent.com/junxnone/update-readme/ghmainpage/merge_kg.py
      python3 merge_kg.py --kgf linux_kg.json xwiki_kg.json aiwiki_kg.json opt_kg.json

  - name: push to gh-page
    shell: bash
    run: |
      REMOTE=https://${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      git config user.email "${{ inputs.actor }}@users.noreply.github.com"
      git config user.name "${{ inputs.actor }}"
      git pull ${REMOTE}
      git add sitemap.md sitehist.md kg.json
      git status
      git commit -am "Update Index"
      git push ${REMOTE}  ${{ inputs.branch }}
